language: c
sudo: required
services:
  - docker
os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo sh -c "curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose";
      sudo chmod +x /usr/local/bin/docker-compose;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew cask install virtualbox;
      brew install docker docker-machine;
      sudo pip install -U docker-compose;
    fi
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      docker-machine create --driver virtualbox docker;
      eval “$(docker-machine env docker)”;
    fi
  - docker-compose run test
  - rake local:test_bin_on_current_target
